### ISSUE TITLE
Icons for skins

### ISSUE THREAD

**Issue by Den1xxx** [nightflyza/YALF#1]
Хранить все иконки шаблонов в папке skins идея так себе, так как количество их растет со временем.
Представляется здравым для всех изображений фреймворка и для скинов в том числе сделать отдельную папку в корне, наример img или images, а там уже подпапку «skins».
Ну или assets или tools —  а там images/skins, css/,  js/ и прочее для всех вспомогательных файлов системы. И лучше это продумать и сделать сразу, пока фреймворк свеж. Иначе заколебаешься потом пути менять по всем файлам.

**Comment by nightflyza** [comment]
Привет Денис.
Я знаю, что хранить носки разбросанными по комнате - заведомо фиговая идея. Вот вообще фиговая, если еще эти носки где-то сверху с люстры свисают. Мне мама еще о этом говорила. 

Только кейс тут не "быть хорошим фремворком" который тупо красивый и продуманный (их и без меня дофига уже, и они объективно сильно умнее и красивше) а предоставлять уровень абстракции и эмулировать существующий бардак и ннкоьорые методы rcms для вполне конкретного, существующего кода. А именно модулей ubilling которые иногда нужно вытаскивать в отдельные стандалон апликухи. И вот да, самое плохое, что исторически они смотрят по прямым ссылкам во все эти иконки и свои ресурсы рандомно разбросанные то в скинах, то в контентах, то еще не пойми куда. Но да, я признаю - это все историческое уебанство, но в текущих реалиях, привести вменяемый вид в рамках кодовой базы всего ubilling почти нереально, учитывая сколько там надо человеко/лет только на рефакторинг и тестирование.

А да, в обратную сторону это тоже должно работать. Тоесть берем модуль написанный с yalf из modules/general, тупо ложим его в modules/general и это должно работать как есть.

 Банальный пример, того как это должно работать на практике: http://covid.ubilling.net.ua/

**Comment by Den1xxx** [comment]
Привет, Ростислав
> Но да, я признаю - это все историческое уебанство, но в текущих реалиях, привести вменяемый вид в рамках кодовой базы всего ubilling почти нереально, учитывая сколько там надо человеко/лет только на рефакторинг и тестирование. 
>
В том-то и дело, что со временем эта проблема укореняется и разрастается. И лучше эту змею задушить в корне. 
Немного пофантазируем. Понадобилось в фреймворке кроме средних сделать мелкие иконки, крупные, сделать переключение шаблонов и вставить в папку 100 шаблонов — вот где жара пойдет, правда? И в подпапки их ведь не распихаешь, в папке skins это будет технически неправильно... Имхо кроме папок шаблонов в skins вообще ничего не должно быть.
А замена путей в готовом движке — это не очень сложная задача. На самом деле, с твоими навыками, я думаю, пару регулярок прогнать по коду редактором и все. Я, когда осознал проблему, справился за пару часов, да потом пару раз где-то ошибки всплыли, исправил. 
Впрочем, я понимаю, что каждый вправе писать как хочет и своим скромным замечанием лишь хотел указать на возможную проблему в будущем. Удачи!

**Comment by nightflyza** [comment]
> В том-то и дело, что со временем эта проблема укореняется и разрастается. И лучше эту змею задушить в корне.

Проблема уже произошла более 10-ти лет назад, и продолжает происходить каждый день :)
Там уже дета 77 человеко/лет легаси кода на который и дышать то не хочется, не то что рефакторить и повторно тестировать.

> Немного пофантазируем. Понадобилось в фреймворке кроме средних сделать мелкие иконки, крупные, сделать переключение шаблонов и вставить в папку 100 шаблонов — вот где жара пойдет, правда?
Тогда я возьму нормальный фреймворк и сделаю все красиво. Хоть ларавель тот же :)

Вся самоцель вот этого вот, просто поддерживать портирование существующей кодовой базы Ubilling as is во внешние приложения по принципу "как есть, главное чтобы быстро и не переписывать". Больше ни для чего оно не нужно.
